### ISSUE TITLE
1080p screen

### ISSUE THREAD

**Issue by flyingipis** [FoxFurry/Destiny2AutoFisher#1]
Hello Foxfurry!

Thank you for the work in this automation!

I was wondering how to get it to work on my 1080p monitor. Do I have to edit the box values?

It starts up no problem but it doesn't seem to interact with the catch fish prompt.

Thank you and have a good day.

**Comment by flyingipis** [comment]
Oh wait it works now!

**Comment by FoxFurry** [comment]
Hey!

Thank you for your question.

It should work on _theoretically_ every resolution as it uses relative positions (relative to your screen resolution).
There are a few issues with text recognition during the fish catch prompt which I will cover in the README which I am working on right now.

The issue is sometimes background behind text prompt has white elements/effects which interrupt text recognition

Then approaching the pond, try to keep the camera on the sky to have it a clear as possible background for recognition.

p.s also, miasma ponds have very bad background which interrupts text recognition

**Comment by flyingipis** [comment]
Noted on this "sky" tip thank you. Yeah i figured might be interference with the ocr as its miasma now! Again my fishing hand and sanity thanks you!
